# Tickler build entry points. The app project is generated by XcodeGen from project.yml.
SHELL := /bin/bash
.SHELLFLAGS := -euo pipefail -c

PREFIX ?= $(HOME)/.local
APP_DIR ?= $(HOME)/Applications
CONFIGURATION ?= Release
DEVELOPMENT_TEAM ?=
DERIVED := build/DerivedData
# Ad-hoc signed unless DEVELOPMENT_TEAM is set: macOS may then ask for permissions again after a rebuild.
SIGN_FLAGS := $(if $(DEVELOPMENT_TEAM),DEVELOPMENT_TEAM=$(DEVELOPMENT_TEAM) CODE_SIGN_STYLE=Automatic -allowProvisioningUpdates,CODE_SIGN_IDENTITY=- CODE_SIGN_STYLE=Manual)

.PHONY: build test lint format project app install dev uninstall clean

build:
	swift build

test:
	swift test

lint:
	swiftlint lint --strict --quiet
	swiftformat --lint .

format:
	swiftformat .

# Regenerated only when project.yml or the list of app files changes: XcodeGen lists files at generation time.
SOURCES_STAMP := build/app-files.txt

project:
	@mkdir -p build
	@find App -type f -not -name '.DS_Store' | sort > $(SOURCES_STAMP).new
	@if [ ! -f Tickler.xcodeproj/project.pbxproj ] || [ project.yml -nt Tickler.xcodeproj/project.pbxproj ] \
		|| ! cmp -s $(SOURCES_STAMP).new $(SOURCES_STAMP); then \
		xcodegen generate --quiet && mv $(SOURCES_STAMP).new $(SOURCES_STAMP); \
	else rm -f $(SOURCES_STAMP).new; fi

app: project
	xcodebuild -project Tickler.xcodeproj -scheme Tickler -configuration $(CONFIGURATION) \
		-derivedDataPath $(DERIVED) \
		$(SIGN_FLAGS) \
		-quiet build

install: app
	swift build -c release --product tickler
	install -d "$(PREFIX)/bin" "$(APP_DIR)"
	install -m 0755 .build/release/tickler "$(PREFIX)/bin/tickler"
	rm -rf "$(APP_DIR)/Tickler.app"
	cp -R "$(DERIVED)/Build/Products/$(CONFIGURATION)/Tickler.app" "$(APP_DIR)/Tickler.app"
	@echo "Installed $(PREFIX)/bin/tickler and $(APP_DIR)/Tickler.app"

# Fast loop: incremental Debug build, replace the installed app, relaunch it.
dev: CONFIGURATION = Debug
dev: app
	install -d "$(APP_DIR)"
	pkill -x Tickler || true
	rm -rf "$(APP_DIR)/Tickler.app"
	cp -R "$(DERIVED)/Build/Products/Debug/Tickler.app" "$(APP_DIR)/Tickler.app"
	open "$(APP_DIR)/Tickler.app"

uninstall:
	rm -f "$(PREFIX)/bin/tickler"
	rm -rf "$(APP_DIR)/Tickler.app"

clean:
	rm -rf .build build Tickler.xcodeproj
