# Tickler build entry points. The app project is generated by XcodeGen from project.yml.
SHELL := /bin/bash
.SHELLFLAGS := -euo pipefail -c

PREFIX ?= $(HOME)/.local
APP_DIR ?= $(HOME)/Applications
CONFIGURATION ?= Release
DEVELOPMENT_TEAM ?=
DERIVED := build/DerivedData
# Signing, first match wins: DEVELOPMENT_TEAM, then the local identity from scripts/create-local-signing-identity.sh,
# then ad hoc. Ad hoc changes with every build, and macOS then forgets the Calendar and Automation permissions.
LOCAL_IDENTITY := Tickler Local Signing
HAS_LOCAL_IDENTITY := $(shell security find-identity -v -p codesigning 2>/dev/null | grep -c '"$(LOCAL_IDENTITY)"')
# SIGN_IDENTITY: an explicit identity, as the release workflow passes its imported certificate.
SIGN_IDENTITY ?=
ifneq ($(SIGN_IDENTITY),)
SIGN_FLAGS := CODE_SIGN_IDENTITY="$(SIGN_IDENTITY)" CODE_SIGN_STYLE=Manual
else ifneq ($(DEVELOPMENT_TEAM),)
SIGN_FLAGS := DEVELOPMENT_TEAM=$(DEVELOPMENT_TEAM) CODE_SIGN_STYLE=Automatic -allowProvisioningUpdates
else ifneq ($(HAS_LOCAL_IDENTITY),0)
SIGN_FLAGS := CODE_SIGN_IDENTITY="$(LOCAL_IDENTITY)" CODE_SIGN_STYLE=Manual
else
SIGN_FLAGS := CODE_SIGN_IDENTITY=- CODE_SIGN_STYLE=Manual
endif

.PHONY: build test lint format project app install dev uninstall clean release

build:
	swift build

test:
	swift test

lint:
	swiftlint lint --strict --quiet
	swiftformat --lint .

format:
	swiftformat .

# Regenerated only when project.yml or the list of app files changes: XcodeGen lists files at generation time.
SOURCES_STAMP := build/app-files.txt

project:
	@mkdir -p build
	@find App -type f -not -name '.DS_Store' | sort > $(SOURCES_STAMP).new
	@if [ ! -f Tickler.xcodeproj/project.pbxproj ] || [ project.yml -nt Tickler.xcodeproj/project.pbxproj ] \
		|| ! cmp -s $(SOURCES_STAMP).new $(SOURCES_STAMP); then \
		xcodegen generate --quiet && mv $(SOURCES_STAMP).new $(SOURCES_STAMP); \
	else rm -f $(SOURCES_STAMP).new; fi

app: project
	xcodebuild -project Tickler.xcodeproj -scheme Tickler -configuration $(CONFIGURATION) \
		-derivedDataPath $(DERIVED) -destination "generic/platform=macOS" \
		$(SIGN_FLAGS) $(XCODEBUILD_EXTRA) \
		-quiet build

install: app
	swift build -c release --product tickler
	install -d "$(PREFIX)/bin" "$(APP_DIR)"
	install -m 0755 .build/release/tickler "$(PREFIX)/bin/tickler"
	rm -rf "$(APP_DIR)/Tickler.app"
	cp -R "$(DERIVED)/Build/Products/$(CONFIGURATION)/Tickler.app" "$(APP_DIR)/Tickler.app"
	@echo "Installed $(PREFIX)/bin/tickler and $(APP_DIR)/Tickler.app"

# Fast loop: incremental Debug build, replace the installed app, relaunch it.
dev: CONFIGURATION = Debug
dev: app
	install -d "$(APP_DIR)"
	pkill -x Tickler || true
	rm -rf "$(APP_DIR)/Tickler.app"
	cp -R "$(DERIVED)/Build/Products/Debug/Tickler.app" "$(APP_DIR)/Tickler.app"
	open "$(APP_DIR)/Tickler.app"

uninstall:
	rm -f "$(PREFIX)/bin/tickler"
	rm -rf "$(APP_DIR)/Tickler.app"

clean:
	rm -rf .build build Tickler.xcodeproj

# Release zip for the Homebrew cask: universal Tickler.app and tickler CLI, both signed with SIGN_IDENTITY.
# The same certificate on every release keeps the permissions macOS granted across upgrades.
DIST := dist
release:
	@test -n "$(VERSION)" || { echo "usage: make release VERSION=x.y.z SIGN_IDENTITY=<name>"; exit 1; }
	@test -n "$(SIGN_IDENTITY)" || { echo "SIGN_IDENTITY is required: an ad hoc release would reset permissions on upgrade"; exit 1; }
	$(MAKE) app CONFIGURATION=Release XCODEBUILD_EXTRA='ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO MARKETING_VERSION=$(VERSION)'
	swift build -c release --product tickler --arch arm64 --arch x86_64
	rm -rf "$(DIST)/tickler-$(VERSION)" && mkdir -p "$(DIST)/tickler-$(VERSION)"
	cp -R "$(DERIVED)/Build/Products/Release/Tickler.app" "$(DIST)/tickler-$(VERSION)/"
	cp .build/apple/Products/Release/tickler "$(DIST)/tickler-$(VERSION)/tickler"
	codesign --force --options runtime --timestamp=none --identifier io.github.pixibixi.tickler.cli \
		--sign "$(SIGN_IDENTITY)" "$(DIST)/tickler-$(VERSION)/tickler"
	codesign --verify --strict "$(DIST)/tickler-$(VERSION)/Tickler.app" "$(DIST)/tickler-$(VERSION)/tickler"
	ditto -c -k --sequesterRsrc "$(DIST)/tickler-$(VERSION)" "$(DIST)/tickler-$(VERSION).zip"
	shasum -a 256 "$(DIST)/tickler-$(VERSION).zip"
