# Tickler build entry points. The app project is generated by XcodeGen from project.yml.
SHELL := /bin/bash
.SHELLFLAGS := -euo pipefail -c

PREFIX ?= $(HOME)/.local
APP_DIR ?= $(HOME)/Applications
CONFIGURATION ?= Release
DEVELOPMENT_TEAM ?=
DERIVED := build/DerivedData
# Ad-hoc signed unless DEVELOPMENT_TEAM is set: macOS may then ask for permissions again after a rebuild.
SIGN_FLAGS := $(if $(DEVELOPMENT_TEAM),DEVELOPMENT_TEAM=$(DEVELOPMENT_TEAM) CODE_SIGN_STYLE=Automatic -allowProvisioningUpdates,CODE_SIGN_IDENTITY=- CODE_SIGN_STYLE=Manual)

.PHONY: build test lint format project app install dev uninstall clean

build:
	swift build

test:
	swift test

lint:
	swiftlint lint --strict --quiet
	swiftformat --lint .

format:
	swiftformat .

# Regenerated only when project.yml changes: a fresh project costs xcodebuild its incremental state.
Tickler.xcodeproj/project.pbxproj: project.yml
	xcodegen generate --quiet

project: Tickler.xcodeproj/project.pbxproj

app: project
	xcodebuild -project Tickler.xcodeproj -scheme Tickler -configuration $(CONFIGURATION) \
		-derivedDataPath $(DERIVED) \
		$(SIGN_FLAGS) \
		-quiet build

install: app
	swift build -c release --product tickler
	install -d "$(PREFIX)/bin" "$(APP_DIR)"
	install -m 0755 .build/release/tickler "$(PREFIX)/bin/tickler"
	rm -rf "$(APP_DIR)/Tickler.app"
	cp -R "$(DERIVED)/Build/Products/$(CONFIGURATION)/Tickler.app" "$(APP_DIR)/Tickler.app"
	@echo "Installed $(PREFIX)/bin/tickler and $(APP_DIR)/Tickler.app"

# Fast loop: incremental Debug build, replace the installed app, relaunch it.
dev: CONFIGURATION = Debug
dev: app
	install -d "$(APP_DIR)"
	pkill -x Tickler || true
	rm -rf "$(APP_DIR)/Tickler.app"
	cp -R "$(DERIVED)/Build/Products/Debug/Tickler.app" "$(APP_DIR)/Tickler.app"
	open "$(APP_DIR)/Tickler.app"

uninstall:
	rm -f "$(PREFIX)/bin/tickler"
	rm -rf "$(APP_DIR)/Tickler.app"

clean:
	rm -rf .build build Tickler.xcodeproj
