#!/usr/bin/env bash
# Conventional Commits check for the commit-msg hook: $1 is the message file.
set -euo pipefail

msg_file="${1:?usage: check-commit-msg.sh <commit-message-file>}"
subject="$(head -n 1 "$msg_file")"

# Merge, revert and fixup commits are generated by git and pass as is.
if [[ "$subject" =~ ^(Merge|Revert|fixup!|squash!)[[:space:]] ]]; then
  exit 0
fi

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z0-9._/-]+\))?!?: .+'
if [[ ! "$subject" =~ $pattern ]]; then
  echo "Commit subject does not follow Conventional Commits: '$subject'" >&2
  echo "Expected: type(scope): description, with type in feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert" >&2
  exit 1
fi

if ((${#subject} > 100)); then
  echo "Commit subject is ${#subject} characters long, keep it at 100 or fewer" >&2
  exit 1
fi
