#!/usr/bin/env bash
# Embeds skills/tickler/SKILL.md into the core, so the CLI and the app install the skill of their own version.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
readonly SOURCE="skills/tickler/SKILL.md"
readonly TARGET="Sources/TicklerCore/Skill/SkillContent.swift"
if grep -q '"""#' "$SOURCE"; then
    echo "$SOURCE contains the raw string terminator \"\"\"#" >&2
    exit 1
fi
{
    printf '// Generated by scripts/embed-skill.sh from %s. Do not edit.\n' "$SOURCE"
    printf 'extension ClaudeSkill {\n    public static let content = #"""\n'
    sed 's/^/    /; s/^    $//' "$SOURCE"
    printf '\n    """#\n}\n'
} > "$TARGET"
echo "embedded $SOURCE into $TARGET"
